### PR TITLE
Add zappi phase setting select

### LINKED ISSUE #509: Add feature to select 1/3/auto phases to be used in ECO+ mode
**Describe the solution you'd like**
The latest zappi app has support to set the number of phases to be used in ECO+ mode (see https://myenergi.info/app-update-3-3-1-t12674.html#p122029)., can be 1, 3, or auto

**Additional context**
See https://github.com/CJNE/pymyenergi/issues/28 for the pymyenergi related issue

### PR DESCRIPTION
**Pull request by jwillemsen**
Add support for zappi phase select, fixed #509 , depends on https://github.com/CJNE/pymyenergi/pull/35

### CODE REVIEW

**Comment by jwillemsen** [comment]
Simplified ZappiChargeModeSelect a little bit, can probably be simplified even more by moving the mapping of internal id to readable string to the translations.

**Comment by jwillemsen** [comment]
Added test extension

**Comment by jwillemsen** [comment]
@CJNE Any remarks on this PR?

**Comment by jwillemsen** [comment]
Lint errors are generic, see https://github.com/CJNE/ha-myenergi/pull/554

**Comment by CJNE** [comment]
Sorry for the delay! It's looking good, thank you!

**Pull request merged**
